name: CI for Windows

on: push

jobs:

  msw:
    strategy:
      fail-fast: false

    runs-on: windows-2025

    steps:
      - uses: actions/checkout@v4
      - uses: shogo82148/actions-setup-perl@v1
        with:
          distribution: strawberry
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: cpanm --installdeps --notest .  || cat /Users/runner/.cpanm/build.log
      - name: Build
        run: |
          perl Makefile.PL
          gmake
      - name: Run Tests
        run: gmake test
