name: CI for Windows

on: push

jobs:

  msw:
    strategy:
      fail-fast: false

    runs-on: windows-latest

    steps:
      - uses: shogo82148/actions-setup-perl@v1
        with:
          distribution: strawberry
      - run: perl -V
      - name: Install Dependencies
        run: cpanm --installdeps .
      - name: Build
        run: |
          perl Makefile.PL
          gmake
      - name: Run Tests
        run: gmake test
